Let's try this instead

diff --git a/.github/workflows/pkgbuild.yml b/.github/workflows/pkgbuild.yml
--- a/.github/workflows/pkgbuild.yml
+++ b/.github/workflows/pkgbuild.yml
@@ -16,7 +16,7 @@ jobs:
             - name: Set up environment
               run: |
                 sudo apt-get update
-                sudo apt-get install -y curl jq base-devel
+                sudo apt-get install -y curl jq
 
             - name: Check latest version
               id: checkver
@@ -39,6 +39,40 @@ jobs:
                 else
                     echo "UPDATENEEDED=false" >> $GITHUB_ENV
                 fi
+
+            - name: Install makepkg
+              if: env.UPDATENEEDED == 'true'
+              run: |
+                sudo apt-get -q -y install --no-install-recommends git pkg-config meson gcc libtool libgpgme-dev libarchive-dev ninja-build libcurl4-openssl-dev libssl-dev curl gettext python3 python3-setuptools dash gawk ca-certificates fakeroot fakechroot libarchive-tools
+                sudo mkdir -p /usr/local/meson
+                sudo git clone https://github.com/mesonbuild/meson.git /usr/local/meson
+                [ -f /usr/bin/meson ] && {
+                    mver=$(/usr/bin/meson --version)
+                    sudo mv /usr/bin/meson /usr/bin/meson-${mver}
+                }
+                if [ -f /usr/local/meson/meson.py ]; then
+                    sudo ln -s /usr/local/meson/meson.py /usr/bin/meson
+                else
+                    echo "ERROR: cannot locate /usr/local/meson/meson.py"
+                    exit 1
+                fi
+                git clone https://gitlab.archlinux.org/pacman/pacman.git
+                cd pacman
+                meson setup -Ddoc=disabled build
+                ninja -C build
+                [ -d build ] || {
+                    echo "Directory pacman/build does not exist. Exiting."
+                    exit 1
+                }
+                cd build
+                grep mirror scripts/libmakepkg/source/git.sh > /dev/null && {
+                    cat scripts/libmakepkg/source/git.sh | sed -e "s/---mirror//" > /tmp/git$$
+                    cp /tmp/git$$ scripts/libmakepkg/source/git.sh
+                    rm -f /tmp/git$$
+                }
+                sudo meson install --no-rebuild --quiet
+                cd ../..
+                sudo rm -rf ./pacman
 
             - name: Update PKGBUILD for all architectures
               if: env.UPDATENEEDED == 'true'
